CREATE TABLE cad_revisao(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(10) NOT NULL, 
sobrenome VARCHAR(35) NOT NULL,
email VARCHAR(30) NOT NULL,
idade VARCHAR(2) NOT NULL,
cpf VARCHAR(11) NOT NULL);

