CREATE TABLE clientes (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
idade INT NOT NULL, 
cidade VARCHAR(50) NOT NULL, 
estado VARCHAR(50) NOT NULL, 
data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
