-- CRIA TABELA COM ID,NOME,CPF,IDADE,TELEFONE,EMAIL

create table cad_clientes(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(20) NOT NULL,
cpf VARCHAR(20) NOT NULL,
idade VARCHAR(3) NOT NULL, 
telefone VARCHAR(20) NOT NULL, 
email VARCHAR(20) NOT NULL);