-- PARTE 05 : ALTERAÇÃO DE ESTRUTURA 

-- a) ADICIONE UM NOVO CAMPO EM ALGUMA TABELA: 

ALTER TABLE clinica_clientes
ADD COLUMN idade INT(3) NOT NULL;

-- b) ALTERE O TIPO OU O TAMANHO DE UM CAMPO EXISTENTE: 

ALTER TABLE clinica_clientes
MODIFY COLUMN idade INT(4) NOT NULL;